### ISSUE TITLE
EventType not exported

### ISSUE THREAD

**Issue by NickAtAccuPS** [jeandudey/tokio-udev#1]
It appears that EventType - necessary for using Event's event_type() - isn't imported/exported from tokio-udev or mio-udev.

Edit: not sure if this is normal practice, so my apologies if this is just noise.

**Comment by jeandudey** [comment]
@NickAtAccuPS Thanks for pointing this.

I have fixed it in cb4f9b2 , and published it to crates.io as the release `0.1.1`.
