### ISSUE TITLE
Incorrect Send/Sync implementation of tokio_udev::MonitorSocket.

### ISSUE THREAD

**Issue by brain0** [jeandudey/tokio-udev#13]
The [Send and Sync implementation](https://github.com/jeandudey/tokio-udev/blob/3e37b9e385402fd45ec022158a10f1325107aa87/tokio-udev/src/lib.rs#L131-L132) of `tokio_udev::MonitorSocket` is incorrect and can be used to trigger undefined behavior:

1) Create a MonitorSocket and poll it until an Event is returned.
2) Send the monitor to another thread and poll it until an Event is returned.
3) On both threads, start and endless loop where you clone the returned event drop the clone again.

This results in unsynchronized calls to [`udev_ref`](https://github.com/Smithay/udev-rs/blob/909f8d31a434560a173acb2a7fbc256d2ca78a55/src/udev.rs#L22-L26) and [`udev_unref`](https://github.com/Smithay/udev-rs/blob/909f8d31a434560a173acb2a7fbc256d2ca78a55/src/udev.rs#L28-L32) on the same `udev` instance. This is not allowed by libudev and triggers undefined behavior.

In particular, no type that contains pointers to libudev objects can possibly be `Send` or `Sync`.

**Comment by jeandudey** [comment]
Hi @brain0 , thanks for pointing it out, gotta remove the Send/Sync traits.

**Comment by jeandudey** [comment]
I've removed the Send/Sync implementations for the MonitorSocket type, if the udev crate doesn't neither this should. Thanks for pointing it out! As a result, [0.7.0](https://github.com/jeandudey/tokio-udev/blob/master/CHANGELOG.md#070) has been released.
