### ISSUE TITLE
Tag new release of `tokio-udev`

### ISSUE THREAD

**Issue by Shinyzenith** [jeandudey/tokio-udev#19]
https://github.com/jeandudey/tokio-udev/commit/ff68101a170efe59cc14acb4b8f2c26abf37a22f the following commit fixes a crucial issue which the downstream project https://GitHub.com/waycrate/swhkd depends on. If a release could be tagged, it would be significantly helpful for us.

**Comment by cyber-sushi** [comment]
Agree, I'm waiting for that fix to finally release my program which depends on tokio_udev

**Comment by jeandudey** [comment]
Tagged as `v0.9.0` and published on crates.io.
